---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DemoRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: list
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: "s3:ListObjects"
            Resource: "*"
      RoleName:
        Fn::Join:
        - '-'
        - - lister
          - Ref: AWS::Region
